### ISSUE TITLE
Valetudo: cannot install

### ISSUE THREAD

**Issue by vladmelnyk** [oleksandr-belei/dreame-vacuum-uk-voice-packs#1]
![Screenshot 2024-02-24 at 23 00 17](https://github.com/oleksandr-belei/dreame-vacuum-uk-voice-packs/assets/16388353/22b071ff-61ab-401b-b479-66d235597404)
![Screenshot 2024-02-24 at 23 01 57](https://github.com/oleksandr-belei/dreame-vacuum-uk-voice-packs/assets/16388353/c04b100d-b1c0-4d53-b4b8-3d712b16de2b)
Firmware version 3102

**Comment by oleksandr-belei** [comment]
I'm sorry to hear you're experiencing trouble installing voice pack with Valetudo. Unfortunately, I'm unable to troubleshoot this directly as I don't have a vacuum flashed with Valetudo. You may find it helpful to reach out to the Valetudo community or consult their documentation for assistance with installation issues specific to their platform.

**Comment by sverdlyuk** [comment]
What URL are you using? Show the full URL

**Comment by vladmelnyk** [comment]
> What URL are you using? Show the full URL



> What URL are you using? Show the full URL

https://github.com/oleksandr-belei/dreame-vacuum-uk-voice-packs/blob/main/voice_packs/uk_female_pensive

**Comment by sverdlyuk** [comment]
> > What URL are you using? Show the full URL
> 
> > What URL are you using? Show the full URL
> 
> https://github.com/oleksandr-belei/dreame-vacuum-uk-voice-packs/blob/main/voice_packs/uk_female_pensive

You use wrong URL. Use this URL (without blob)

https://github.com/oleksandr-belei/dreame-vacuum-uk-voice-packs/raw/main/voice_packs/uk_female_pensive

**Comment by vladmelnyk** [comment]
thanks @sverdlyuk
